---
- name: preparing web directories
  file: path=$item
        state=directory
        owner=root group=root mode=0755
  with_items:
    - /home/www/etc/nginx/sites/
    - /home/www/sites/default/htdocs/

- name: configure default site
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root group=root mode=0644
  with_items:
    - { src: 'default.conf', dest: '/home/www/etc/nginx/sites/default.conf' }
    - { src: 'index.html', dest: '/home/www/sites/default/htdocs/index.html' }
    - { src: 'info.php', dest: '/home/www/sites/default/htdocs/info.php' }
  notify: restart nginx
