---
- name: install php
  apt: pkg=$item
       state=present
  with_items:
    - php5-cgi
    - php5-fpm

- name: configure php-fpm
  template: src=www.conf
            dest=/etc/php5/fpm/pool.d/www.conf
            owner=root group=root mode=0644
  notify: restart php-fpm

- name: start php-fpm
  service: name=php5-fpm state=started enabled=true
