
- name: copy sources.list
  template: src=sources.list
            dest=/etc/apt/sources.list
            owner=root mode=0644

- name: update packages cache
  apt: update_cache=yes cache_valid_time=86400
