---
- name: install basic system
  apt: pkg=$item
       state=present
  with_items:
    - bridge-utils
    - mdadm
    - xfsprogs
    - btrfs-tools

    - build-essential

    - traceroute
    - sysstat
    - iotop
    - htop
    - ifstat
    - lm-sensors
